name: Build Smart Contracts

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Compile contracts
      run: npx hardhat compile

    - name: Run tests
      run: npx hardhat test

    - name: Test Coverage on pull request
      if: github.event_name == 'pull_request'
      run: npx hardhat coverage

    - name: Publish Contract Artifact
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PUSH_TXT_ARTIFACT_TOKEN }}
        external_repository: doughgle/contract-artifacts
        publish_branch: ${{ github.ref }}
        publish_dir: ./artifacts/contracts
        exclude_assets: '**/*.dbg.json'
        commit_message: ${{ github.event.head_commit.message }}